class OpportunityPageSelectors:
    """Class for One Button Opportunity Page"""

    FIRST_NAME_MANDATORY_ERROR = "//div[text()=' First Name is required ']"
    LAST_NAME_MANDATORY_ERROR = "//div[text()=' Last Name is required ']"
    EMAIL_MANDATORY_ERROR = "//div[text()=' Valid Email is required ']"
    PHONE_NUMBER_MANDATORY_ERROR = "//div[text()=' Valid Phone Number is required ']"
    VIEW_ROOF_PROPOSAL_CASH = "(//a[@title='View Proposal'])[1]"
    CUST_INFO_FIRST_NAME = "//input[@formcontrolname='firstName']"
    CUST_INFO_LAST_NAME = "//input[@formcontrolname='lastName']"
    CUST_INFO_EMAIL = "//input[@formcontrolname='email']"
    CUST_INFO_PHONE = "//input[@formcontrolname='phoneNumber']"
    OPPORTUNITY_INTEREST_DROP_DOWN_TRUE = "//nz-collapse-panel[@nzheader='Opportunity Interest']//*[@style='transform: rotate(90deg)']"
    OPPORTUNITY_INTEREST_DROP_DOWN_FALSE = "(//nz-collapse-panel[@nzheader='Opportunity Interest']//i)[1]"
    INSTALLATION_ADDRESS_DROP_DOWN_TRUE = "//nz-collapse-panel[@nzheader='Installation Address']//*[@style='transform: rotate(90deg)']"
    INSTALLATION_ADDRESS_DROP_DOWN_FALSE = "(//nz-collapse-panel[@nzheader='Installation Address']//i)"
    OPPORTUNITY_INTEREST_DROPDOWN = "//div[@role='tab'][text()='Opportunity Interest']//i"
    INSTALLATION_ADDRESS_DROPDOWN = "//div[@role='tab'][text()='Installation Address']//i"
    BLACK_KNIGHT_SYNC_SYNCING = "//button//span[normalize-space()='Sync Contacts on Title']"
    CHECKLIST_ERROR = "//li[contains(@class, 'background-danger')]"
    CUSTOMER_INFORMATION_CARDS = "(//nz-list-item[contains(@class, 'customer-contact')])"
    SOLAR_PRODUCT = "//button[@id='financeProduct-Solar']"
    ROOF_PRODUCT = "//span[normalize-space()='Roof']"
    BATTERY_PRODUCT = "//button[@id='financeProduct-Battery']"
    RRR_PRODUCT = "//button[@id='financeProduct-RRR']"
    ADD_CONTACT_BTN = "//button[@id='add-contact-btn']"
    CUSTOMER_INFORMATION_LABEL = "//span[normalize-space()='CUSTOMER INFORMATION']"
    CUSTOMER_INFORMATION_PHONE_TYPE = "//select[@name='phoneType']"
    CUSTOMER_INFORMATION_CONTACT_TYPE = "//select[@name='preferredContact']"
    CUSTOMER_INFORMATION_CONTACT_METHOD = "//select[@name='preferredContactMethod']"

    SUNNOVA_UN_SYNCED = "//button[contains(@class, 'unsyced') and not(contains(@class, 'icon'))]"
    LEAD_NOT_FOUND_ERROR = "//td[text()='Lead not found in Sunnova.']"

    LEAD_NOT_FOUND_BLACK_KNIGHT = "//td[contains(text(),'Lead not found in Black Knight.')]"

    CREATE_NEW_SUNNOVA_LEAD_BTN = "//button[normalize-space()='Create New Sunnova Lead']"
    BLACK_KNIGHT_SYNCED = "//button[contains(@class, 'unsyced')]//span[contains(text(),'Black Knight Title Check')]"

    SUNNOVA_FAILED = "//li[contains(@class,'form-stepper-failed')]"
    SUNNOVA_PENDING = "//li[contains(@class,'form-stepper-pending')]"
    CLOSE_POPUP = "//button[normalize-space()='Close']"
    SUNNOVA_SUCCESSFUL = "//li[contains(@class,'form-stepper-active')]"

    CHECK_BOX_SYNC_POP_UP = "//div[contains(@class, 'ant-modal-content')]//input[@type='checkbox'][1]"
    ADDRESS_MISMATCH_POPUP = "(//div[contains(@class, 'ant-modal-content')])[2]"
    ADDRESS_MISMATCH_POPUP_OK = "//span[contains(text(),'OK')]"
    POPUP = "//div[contains(@class, 'ant-modal-content')]"
    CLOSE_HOME_POPUP = "//i[@class='anticon ant-modal-close-icon anticon-close ng-star-inserted']"
    CLOSE_HOME_POPUP_CSS = "i[class='anticon ant-modal-close-icon anticon-close ng-star-inserted']"
    SYNC_BUTTON_SUNNOVA_LEAD_COUNT = "(//button//span[text()=' Sync '])"
    SYNC_BUTTON_SUNNOVA_LEAD = "(//button//span[text()=' Sync '])[1]"
    UTILITY_INFORMATION_TEXT = "//div[contains(text(),'Utility Information')]"
    SOLAR_SELECTED = "//button[@id='financeProduct-Solar' and contains(@class, 'active-button')]"
    ROOF_SELECTED = "//button[@id='financeProduct-Roof' and contains(@class, 'active-button')]"
    BATTERY_SELECTED = "//button[@id='financeProduct-Battery' and contains(@class, 'active-button')]"
    RRR_SELECTED = "//button[@id='financeProduct-RRR' and contains(@class, 'active-button')]"
    FINANCE_ERROR = "//div[contains(text(), 'Please choose finance partner ')]"
    OPP_PAGE_VERIFY = "//div[contains(text(),'Products')]"
    UTILITY_CHECK = "//button[contains(@class, 'active')]//span[contains(text(),'On Utility Bill')]"
    UTILITY_UN_CHECK = "//button[not(contains(@class, 'active'))]//span[contains(text(), 'On Utility Bill')]"
    SAVE = "//span[text()=' SAVE ']"
    SAVE_CSS = "//span[text()=' SAVE ']"
    QUOTE_SIGN = "//i[contains(@class, 'dollar-sign')]"
    SYS_DESIGN = "//span[text()='DESIGN']"
    UTILITY_PAGE = "//span[text()='UTILITY']"
    NEXT = "//span[text()=' NEXT ']"
    NEXT_BTN_OP_PAGE = "//button[@id='next-btn']"
    SYNC_ERROR_NEXT_BUTTON = "//div[contains(text(), 'You have chosen “Sunnova” as finance partner for the following product(s)')]"
    SYNC_ERROR_NEXT_BUTTON_POPUP_OK = "//span[contains(text(),'OK')]"
    PRIMARY_CONTACT_CHECK = "//button[(contains(@class, 'active'))]//span[contains(text(), ' Primary Contact ')]"
    PRIMARY_CONTACT_UNCHECK = "//button[not(contains(@class, 'active'))]//span[contains(text(), ' Primary Contact ')]"

    FINANCE_SOLAR = "//select[@id='financeMethod-Solar']"
    FINANCE_ROOF = "//select[@id='financeMethod-Roof']"
    FINANCE_BATTERY = "//select[@id='financeMethod-Battery']"
    FINANCE_RRR = "//select[@id='financeMethod-RRR']"

    SUNNOVA_SYNCED_BTN = "//button[@id='sunnova-sync-btn' and not(contains(@class, 'unsyced'))]"
    SOLAR_LEAD_ID = "//div[contains(text(), 'Solar')]//following::span[1]"
    ROOF_LEAD_ID = "//div[contains(text(), 'Roof')]//following::span[1]"
    BATTERY_LEAD_ID = "//div[contains(text(), 'Battery')]//following::span[1]"
    RRR_LEAD_ID = "//div[contains(text(), 'RRR')]//following::span[1]"

    def card_len(id):
        el = f"(//nz-list-item[contains(@class, 'customer-contact')])[{id}]"
        return el
