class DesignPageSelectors:
    """Class for One Button System Design Page"""
    DESIGN_BATTERY_TAB = "//span[text()=' Battery ']"
    DESIGN_SOLAR_TAB = "//span[text()=' Solar ']"
    DESIGN_ROOF_TAB = "//span[text()=' Roof ']"
    DESIGN_RRR_TAB = "//span[text()=' RRR ']"
    MANUFACTURER_ID_SELECT = "//select[@formcontrolname='ManufacturerId']"
    ROOF_SQUARE_OVERRIDE_FIELD = "//input[@formcontrolname='RoofSquareOverride']"
    RRR_SYSTEM_SIZE = "//input[@formcontrolname='RR_System_Size']"
    BATTERY_MANUFACTURER = "//select[@formcontrolname='manufactureName']"
    BATTERY_MANUFACTURER_NAME = "//select[@formcontrolname='Name']"
    BATTERY_QUANTITY = "//select[@formcontrolname='Quantity']"
    SYNC_STATUS_POP_UP = "//div[@id='syncSunnovaCheckListSection']"

    SYSTEM_DESIGN_PAGE_TITLE_SOLAR = "//div[contains(text(),'Design Array')]"
    SYSTEM_DESIGN_PAGE_TITLE_ROOF = "//div[contains(text(),'Roof Projects')]"
    SYSTEM_DESIGN_PAGE_TITLE_BATTERY = "//div[contains(text(),'Battery Information')]"
    SYS_DESIGN_ARRAY = "(//nz-list-item[contains(@class, 'array-item')])[1]"
    SOLAR_DATA_ERROR = "//span[contains(@class, 'error_message')]"
    SYSTEM_SIZE = "(//div[@id='solar-product-design']//strong)[1]"
    SYSTEM_DESIGN_NEXT_BUTTON = "//button//span[normalize-space()='NEXT']"
    BATTERY_TAB_ERROR = "//div[contains(@class, 'invalid-feedbacks')]"
    ROOF_MANUFACTURER = "//select[@formcontrolname='ManufacturerId']"
    ROOF_PRODUCT = "//select[@formcontrolname='RoofProduct']"
